version: '2'
services:
  web_node1:
    build: ./node1
    volumes:
      - ../:/rbshark
    tty: true
    environment:
      TZ: Asia/Tokyo
    networks:
      - rbwebshark_net
    ports:
      - 3000:3000
  web_node2:
    build: ./node2
    volumes:
      - ../:/rbwebshark
    tty: true
    environment:
      TZ: Asia/Tokyo
    networks:
      - rbwebshark_net
networks:
  rbwebshark_net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 192.168.100.0/24
        - subnet: 2001:db8:100::/64
          gateway: 2001:db8:100::1
